@baseUrl = http://localhost:3001/api/v2

### Read all users
GET {{baseUrl}}/users/pg


### Create a new user
POST {{baseUrl}}/users/pg
Content-Type: application/json

{
  "username": "Chirasak",
  "email": "dearchirasak4@example.com",
  "password": "pass123" 
}


### Update a user
PUT {{baseUrl}}/users/pg/827be652-6da3-4e91-ba39-809986f943be
Content-Type: application/json

{
  "username": "ChirasakHellow",
  "email": "Hello@example.com",
  "password": "newpassword123"
}


### Delete User
DELETE {{baseUrl}}/users/pg/1


